require('dotenv').config();
const express = require('express');
const cors = require('cors');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const { GoogleGenerativeAI } = require('@google/generative-ai');

const app = express();
const port = process.env.PORT || 3000;

const storage = multer.diskStorage({
    destination: (req, file, cb) => {
        if (!fs.existsSync('uploads/')) fs.mkdirSync('uploads/');
        cb(null, 'uploads/');
    },
    filename: (req, file, cb) => {
        cb(null, Date.now() + path.extname(file.originalname));
    }
});
const upload = multer({ storage: storage });

app.use(cors());
app.use(express.json());
app.use(express.static('public'));

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

function fileToGenerativePart(path, mimeType) {
    return {
        inlineData: {
            data: Buffer.from(fs.readFileSync(path)).toString("base64"),
            mimeType
        },
    };
}

app.post('/analyze-bug', upload.single('video'), async (req, res) => {
    try {
        if (!req.file) return res.status(400).json({ success: false, error: "No video file uploaded." });

        console.log(`--- Analyzing video for Boss: ${req.file.filename} ---`);
        
        const model = genAI.getGenerativeModel({ model: "gemini-3-flash-preview" });

        // PROMPT UPGRADED: Added Playwright Automation script generation
        const prompt = `Act as a Senior QA Automation Engineer. Analyze the provided screen recording.
        Generate a professional Bug Report in English.
        
        STRUCTURE:
        1. **Bug Title**: Concise.
        2. **Severity**: (Critical/High/Medium/Low).
        3. **Description**: What is the issue?
        4. **Steps to Reproduce**: Detailed list.
        5. **Expected vs Actual Result**.
        
        BONUS SECTION:
        6. **Playwright Test Script**: Provide a Node.js Playwright script that mimics the user's steps shown in the video. Use placeholders for selectors if they are not clear, but try to be as accurate as possible.

        Final signature: "**Report & Automation generated by Gemini 3 Flash Autopilot**".`;

        const videoPart = fileToGenerativePart(req.file.path, req.file.mimetype);
        const result = await model.generateContent([prompt, videoPart]);
        const response = await result.response;
        const text = response.text();

        fs.unlinkSync(req.file.path);

        console.log("✅ Analysis and Automation script generated.");
        res.json({ success: true, message: text });

    } catch (error) {
        console.error("❌ Error:", error.message);
        if (req.file) fs.unlinkSync(req.file.path);
        res.status(500).json({ success: false, error: error.message });
    }
});

app.listen(port, () => {
    console.log(`🚀 QA Autopilot (with Automation) running on http://localhost:${port}`);
});